// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddBalance(ctx context.Context, arg AddBalanceParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (sql.Result, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (sql.Result, error)
	DeleteAccount(ctx context.Context, id sql.NullInt64) error
	GetAccount(ctx context.Context, id sql.NullInt64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id sql.NullInt64) (Account, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
}

var _ Querier = (*Queries)(nil)
