// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: transfer.sql

package db

import (
	"context"
	"database/sql"
)

const createTransfer = `-- name: CreateTransfer :execresult
insert into transfer (from_id, to_id, amount) values (?, ?, ?)
`

type CreateTransferParams struct {
	FromID int64 `json:"fromID"`
	ToID   int64 `json:"toID"`
	Amount int64 `json:"amount"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransfer, arg.FromID, arg.ToID, arg.Amount)
}
