package main

import (
	"context"
	"fmt"
	"go_learning/gin_example/models"
	"go_learning/gin_example/pkg/gredis"
	"go_learning/gin_example/pkg/logging"
	"go_learning/gin_example/pkg/setting"
	"go_learning/gin_example/routers"
	"log"
	"net/http"
	"os"
	"os/signal"
	"time"
	//_ "go_learning/gin_example/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {

	setting.Setup()
	models.SetUp()
	logging.Setup()
	gredis.Setup()

	router := routers.InitRouter()

	s := &http.Server{
		Addr:           fmt.Sprintf(":%d", setting.ServerSetting.HttpPort),
		Handler:        router,
		ReadTimeout:    setting.ServerSetting.ReadTimeout,
		WriteTimeout:   setting.ServerSetting.WriteTimeout,
		MaxHeaderBytes: 1 << 20,
	}

	go func() {
		if err := s.ListenAndServe(); err != nil {
			log.Printf("Listen: %s\n", err)
		}
	}()

	quit := make(chan os.Signal)
	signal.Notify(quit, os.Interrupt)
	<-quit

	log.Println("Shutdown Server ...")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := s.Shutdown(ctx); err != nil {
		log.Fatal("Server Shutdown: ", err)
	}

	log.Println("Server exiting")
}
