// Code generated by ent, DO NOT EDIT.

package db

import (
	"go-learning/grpc/pcbook/db/laptop"
	"go-learning/grpc/pcbook/db/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	laptopFields := schema.Laptop{}.Fields()
	_ = laptopFields
	// laptopDescUID is the schema descriptor for uid field.
	laptopDescUID := laptopFields[0].Descriptor()
	// laptop.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	laptop.UIDValidator = laptopDescUID.Validators[0].(func(string) error)
	// laptopDescBrand is the schema descriptor for brand field.
	laptopDescBrand := laptopFields[1].Descriptor()
	// laptop.BrandValidator is a validator for the "brand" field. It is called by the builders before save.
	laptop.BrandValidator = laptopDescBrand.Validators[0].(func(string) error)
	// laptopDescName is the schema descriptor for name field.
	laptopDescName := laptopFields[2].Descriptor()
	// laptop.NameValidator is a validator for the "name" field. It is called by the builders before save.
	laptop.NameValidator = laptopDescName.Validators[0].(func(string) error)
	// laptopDescWeight is the schema descriptor for weight field.
	laptopDescWeight := laptopFields[3].Descriptor()
	// laptop.DefaultWeight holds the default value on creation for the weight field.
	laptop.DefaultWeight = laptopDescWeight.Default.(float64)
	// laptopDescPriceRmb is the schema descriptor for price_rmb field.
	laptopDescPriceRmb := laptopFields[4].Descriptor()
	// laptop.DefaultPriceRmb holds the default value on creation for the price_rmb field.
	laptop.DefaultPriceRmb = laptopDescPriceRmb.Default.(uint32)
	// laptopDescReleaseYear is the schema descriptor for release_year field.
	laptopDescReleaseYear := laptopFields[5].Descriptor()
	// laptop.DefaultReleaseYear holds the default value on creation for the release_year field.
	laptop.DefaultReleaseYear = laptopDescReleaseYear.Default.(uint32)
	// laptopDescCreatedAt is the schema descriptor for created_at field.
	laptopDescCreatedAt := laptopFields[6].Descriptor()
	// laptop.DefaultCreatedAt holds the default value on creation for the created_at field.
	laptop.DefaultCreatedAt = laptopDescCreatedAt.Default.(func() time.Time)
	// laptopDescUpdatedAt is the schema descriptor for updated_at field.
	laptopDescUpdatedAt := laptopFields[7].Descriptor()
	// laptop.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	laptop.DefaultUpdatedAt = laptopDescUpdatedAt.Default.(func() time.Time)
	// laptop.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	laptop.UpdateDefaultUpdatedAt = laptopDescUpdatedAt.UpdateDefault.(func() time.Time)
}
