// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: grpc/pcbook/proto/laptop_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLaptopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Laptop *Laptop `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
}

func (x *CreateLaptopReq) Reset() {
	*x = CreateLaptopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pcbook_proto_laptop_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLaptopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLaptopReq) ProtoMessage() {}

func (x *CreateLaptopReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pcbook_proto_laptop_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLaptopReq.ProtoReflect.Descriptor instead.
func (*CreateLaptopReq) Descriptor() ([]byte, []int) {
	return file_grpc_pcbook_proto_laptop_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLaptopReq) GetLaptop() *Laptop {
	if x != nil {
		return x.Laptop
	}
	return nil
}

type CreateLaptopResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateLaptopResp) Reset() {
	*x = CreateLaptopResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pcbook_proto_laptop_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLaptopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLaptopResp) ProtoMessage() {}

func (x *CreateLaptopResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pcbook_proto_laptop_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLaptopResp.ProtoReflect.Descriptor instead.
func (*CreateLaptopResp) Descriptor() ([]byte, []int) {
	return file_grpc_pcbook_proto_laptop_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLaptopResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_grpc_pcbook_proto_laptop_service_proto protoreflect.FileDescriptor

var file_grpc_pcbook_proto_laptop_service_proto_rawDesc = []byte{
	0x0a, 0x26, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x26, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61,
	0x70, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x06, 0x6c, 0x61, 0x70, 0x74, 0x6f,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x61, 0x70,
	0x74, 0x6f, 0x70, 0x52, 0x06, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x22, 0x22, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32,
	0x4a, 0x0a, 0x0d, 0x4c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x39, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x70, 0x74, 0x6f, 0x70,
	0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x70, 0x74,
	0x6f, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x42, 0x12, 0x5a, 0x10, 0x2e,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_pcbook_proto_laptop_service_proto_rawDescOnce sync.Once
	file_grpc_pcbook_proto_laptop_service_proto_rawDescData = file_grpc_pcbook_proto_laptop_service_proto_rawDesc
)

func file_grpc_pcbook_proto_laptop_service_proto_rawDescGZIP() []byte {
	file_grpc_pcbook_proto_laptop_service_proto_rawDescOnce.Do(func() {
		file_grpc_pcbook_proto_laptop_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_pcbook_proto_laptop_service_proto_rawDescData)
	})
	return file_grpc_pcbook_proto_laptop_service_proto_rawDescData
}

var file_grpc_pcbook_proto_laptop_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_pcbook_proto_laptop_service_proto_goTypes = []interface{}{
	(*CreateLaptopReq)(nil),  // 0: pb.CreateLaptopReq
	(*CreateLaptopResp)(nil), // 1: pb.CreateLaptopResp
	(*Laptop)(nil),           // 2: pb.Laptop
}
var file_grpc_pcbook_proto_laptop_service_proto_depIdxs = []int32{
	2, // 0: pb.CreateLaptopReq.laptop:type_name -> pb.Laptop
	0, // 1: pb.LaptopService.CreateLaptop:input_type -> pb.CreateLaptopReq
	1, // 2: pb.LaptopService.CreateLaptop:output_type -> pb.CreateLaptopResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_pcbook_proto_laptop_service_proto_init() }
func file_grpc_pcbook_proto_laptop_service_proto_init() {
	if File_grpc_pcbook_proto_laptop_service_proto != nil {
		return
	}
	file_grpc_pcbook_proto_laptop_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_pcbook_proto_laptop_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLaptopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pcbook_proto_laptop_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLaptopResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pcbook_proto_laptop_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pcbook_proto_laptop_service_proto_goTypes,
		DependencyIndexes: file_grpc_pcbook_proto_laptop_service_proto_depIdxs,
		MessageInfos:      file_grpc_pcbook_proto_laptop_service_proto_msgTypes,
	}.Build()
	File_grpc_pcbook_proto_laptop_service_proto = out.File
	file_grpc_pcbook_proto_laptop_service_proto_rawDesc = nil
	file_grpc_pcbook_proto_laptop_service_proto_goTypes = nil
	file_grpc_pcbook_proto_laptop_service_proto_depIdxs = nil
}
