version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gorm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gorm_example
      MYSQL_USER: gorm_user
      MYSQL_PASSWORD: gorm_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: gorm_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  adminer:
    image: adminer
    container_name: gorm_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
  redis_data: 